[package]
name = "misc-behaviours"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mockall = { git = "https://github.com/asomers/mockall.git", branch = "master" }
